### ISSUE TITLE
cosa c'è dentro il vaccino?

### ISSUE THREAD

**Issue by PirateOfTheCaribbean** [klamerja/sussy#12]
magari gli spaciughi??👀

**Comment by PirateOfTheCaribbean** [comment]
almeno l'eroina sai come la fanno

**Comment by klamerja** [comment]
![image](https://github.com/klamerja/sussy/assets/43652136/5a4ebab3-441c-43e9-a097-ca78558ff152)

**Comment by PirateOfTheCaribbean** [comment]
capito, grazie
